/**
 * webtrees: online genealogy
 * Copyright (C) 2026 webtrees development team
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import { AbstractEncoding } from './abstract-encoding.js';

/**
 * Convert between UTF-8 and ASCII.
 * Ported from app/Encodings/ASCII.php (task 16).
 */
export class ASCII extends AbstractEncoding {
  static NAME = 'ASCII';

  static TO_UTF8 = {
    '\x80': "\ufffd",
    '\x81': "\ufffd",
    '\x82': "\ufffd",
    '\x83': "\ufffd",
    '\x84': "\ufffd",
    '\x85': "\ufffd",
    '\x86': "\ufffd",
    '\x87': "\ufffd",
    '\x88': "\ufffd",
    '\x89': "\ufffd",
    '\x8A': "\ufffd",
    '\x8B': "\ufffd",
    '\x8C': "\ufffd",
    '\x8D': "\ufffd",
    '\x8E': "\ufffd",
    '\x8F': "\ufffd",
    '\x90': "\ufffd",
    '\x91': "\ufffd",
    '\x92': "\ufffd",
    '\x93': "\ufffd",
    '\x94': "\ufffd",
    '\x95': "\ufffd",
    '\x96': "\ufffd",
    '\x97': "\ufffd",
    '\x98': "\ufffd",
    '\x99': "\ufffd",
    '\x9A': "\ufffd",
    '\x9B': "\ufffd",
    '\x9C': "\ufffd",
    '\x9D': "\ufffd",
    '\x9E': "\ufffd",
    '\x9F': "\ufffd",
    '\xA0': "\ufffd",
    '\xA1': "\ufffd",
    '\xA2': "\ufffd",
    '\xA3': "\ufffd",
    '\xA4': "\ufffd",
    '\xA5': "\ufffd",
    '\xA6': "\ufffd",
    '\xA7': "\ufffd",
    '\xA8': "\ufffd",
    '\xA9': "\ufffd",
    '\xAA': "\ufffd",
    '\xAB': "\ufffd",
    '\xAC': "\ufffd",
    '\xAD': "\ufffd",
    '\xAE': "\ufffd",
    '\xAF': "\ufffd",
    '\xB0': "\ufffd",
    '\xB1': "\ufffd",
    '\xB2': "\ufffd",
    '\xB3': "\ufffd",
    '\xB4': "\ufffd",
    '\xB5': "\ufffd",
    '\xB6': "\ufffd",
    '\xB7': "\ufffd",
    '\xB8': "\ufffd",
    '\xB9': "\ufffd",
    '\xBA': "\ufffd",
    '\xBB': "\ufffd",
    '\xBC': "\ufffd",
    '\xBD': "\ufffd",
    '\xBE': "\ufffd",
    '\xBF': "\ufffd",
    '\xC0': "\ufffd",
    '\xC1': "\ufffd",
    '\xC2': "\ufffd",
    '\xC3': "\ufffd",
    '\xC4': "\ufffd",
    '\xC5': "\ufffd",
    '\xC6': "\ufffd",
    '\xC7': "\ufffd",
    '\xC8': "\ufffd",
    '\xC9': "\ufffd",
    '\xCA': "\ufffd",
    '\xCB': "\ufffd",
    '\xCC': "\ufffd",
    '\xCD': "\ufffd",
    '\xCE': "\ufffd",
    '\xCF': "\ufffd",
    '\xD0': "\ufffd",
    '\xD1': "\ufffd",
    '\xD2': "\ufffd",
    '\xD3': "\ufffd",
    '\xD4': "\ufffd",
    '\xD5': "\ufffd",
    '\xD6': "\ufffd",
    '\xD7': "\ufffd",
    '\xD8': "\ufffd",
    '\xD9': "\ufffd",
    '\xDA': "\ufffd",
    '\xDB': "\ufffd",
    '\xDC': "\ufffd",
    '\xDD': "\ufffd",
    '\xDE': "\ufffd",
    '\xDF': "\ufffd",
    '\xE0': "\ufffd",
    '\xE1': "\ufffd",
    '\xE2': "\ufffd",
    '\xE3': "\ufffd",
    '\xE4': "\ufffd",
    '\xE5': "\ufffd",
    '\xE6': "\ufffd",
    '\xE7': "\ufffd",
    '\xE8': "\ufffd",
    '\xE9': "\ufffd",
    '\xEA': "\ufffd",
    '\xEB': "\ufffd",
    '\xEC': "\ufffd",
    '\xED': "\ufffd",
    '\xEE': "\ufffd",
    '\xEF': "\ufffd",
    '\xF0': "\ufffd",
    '\xF1': "\ufffd",
    '\xF2': "\ufffd",
    '\xF3': "\ufffd",
    '\xF4': "\ufffd",
    '\xF5': "\ufffd",
    '\xF6': "\ufffd",
    '\xF7': "\ufffd",
    '\xF8': "\ufffd",
    '\xF9': "\ufffd",
    '\xFA': "\ufffd",
    '\xFB': "\ufffd",
    '\xFC': "\ufffd",
    '\xFD': "\ufffd",
    '\xFE': "\ufffd",
    '\xFF': "\ufffd",
  };
}
