/**
 * webtrees: online genealogy
 * Copyright (C) 2026 webtrees development team
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

// The setup wizard's language list, read from golden/setup_languages.json
// (generated by bin/characterize_setup_languages.php from the real
// ModuleService::setupLanguages() - see that script's header comment
// and docs/php-to-js-migration/phase5-postgres-setup-cli.md). Loaded
// directly at runtime rather than duplicated into a hand-maintained JS
// array, so there's exactly one source of truth to keep in sync when
// webtrees adds/removes a language module.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const REPO_ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const LANGUAGES_JSON_PATH = path.join(REPO_ROOT, 'golden', 'setup_languages.json');

export const DEFAULT_LANGUAGE_TAG = 'en-US';

let cachedLanguages = null;

/**
 * @returns {{languageTag: string, endonym: string}[]}
 */
export function loadSetupLanguages() {
  cachedLanguages ??= JSON.parse(readFileSync(LANGUAGES_JSON_PATH, 'utf8'));

  return cachedLanguages;
}

/**
 * Case-insensitive lookup by language tag (e.g. a --lang flag value) -
 * returns the 0-based index into loadSetupLanguages(), or -1 if the tag
 * isn't one of the real supported languages.
 */
export function findLanguageIndex(languageTag) {
  const languages = loadSetupLanguages();
  const needle = languageTag.toLowerCase();

  return languages.findIndex((language) => language.languageTag.toLowerCase() === needle);
}
