// Golden fixtures for lib/encodings/* store raw bytes as hex strings (since
// JSON can't hold arbitrary binary safely). These convert between hex and
// the "byte string" convention documented in lib/encodings/abstract-encoding.js
// (one JS UTF-16 code unit per raw byte, value 0-255).

export function hexToByteString(hex) {
  let out = '';
  for (let i = 0; i < hex.length; i += 2) {
    out += String.fromCharCode(parseInt(hex.slice(i, i + 2), 16));
  }
  return out;
}

export function byteStringToHex(byteString) {
  let out = '';
  for (let i = 0; i < byteString.length; i++) {
    out += byteString.charCodeAt(i).toString(16).padStart(2, '0');
  }
  return out;
}

// Encodes a real (decoded) Unicode JS string as UTF-8 bytes, hex-encoded —
// for comparing against golden fixtures generated by PHP's bin2hex() on a
// native UTF-8 PHP string. Not the same as byteStringToHex(): a "text"
// value (see lib/encodings/abstract-encoding.js) can contain code points
// above 255, which byteStringToHex() would mis-encode.
const ENCODER = new TextEncoder();
const DECODER = new TextDecoder('utf-8');

export function textToUtf8Hex(text) {
  return Buffer.from(ENCODER.encode(text)).toString('hex');
}

// The reverse: hex-encoded UTF-8 bytes -> a real Unicode JS string.
export function hexToUtf8Text(hex) {
  return DECODER.decode(Buffer.from(hex, 'hex'));
}
